### ISSUE TITLE
fix variable assignments

### ISSUE THREAD

**Issue by dcaratti** [dcaratti/packetdrill#1]

**Comment by dcaratti** [comment]
variable assignment in mp_capable_no_cs doesn't seem to work properly, see 


```[root@rhel7 net]# cat mptcp/simple/simple.pkt
// Test mp_capable mptcp option, first syn sent by packetdrill
 
+0  socket(..., SOCK_STREAM, IPPROTO_MPTCP) = 3
+0  setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
 
+0  bind(3, ..., ...) = 0
+0  listen(3, 1) = 0
+0  < S 0:0(0) win 32792 <mss 1000,sackOK,nop,nop,nop,wscale 8,mp_capable_no_cs a>
+0  > S. 0:0(0) ack 1 win 65535 <mss 1460,nop,nop,sackOK,nop,wscale 8,mp_capable_no_cs b a>
+0.1  < . 1:1(0) ack 1 win 257 <mp_capable_no_cs a b>
+0  accept(3, ..., ...) = 4
 
[root@rhel7 net]# tcpdump -tnni any tcp port 8080 -w prova.pcap &
[2] 23977
[root@rhel7 net]# tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
 
[root@rhel7 net]# ./packetdrill/packetdrill mptcp/simple/simple.pkt
[root@rhel7 net]# fg
tcpdump -tnni any tcp port 8080 -w prova.pcap
^C5 packets captured
5 packets received by filter
0 packets dropped by kernel
[root@rhel7 net]# tcpdump -tnnr prova.pcap
reading from file prova.pcap, link-type LINUX_SLL (Linux cooked)
IP 192.0.2.1.46505 > 192.168.175.218.8080: Flags [S], seq 0, win 32792, options [mss 1000,sackOK,nop,nop,nop,wscale 8,mptcp capable {0x837fb64bfcf2b75d}], length 0
IP 192.168.175.218.8080 > 192.0.2.1.46505: Flags [S.], seq 1176234094, ack 1, win 65535, options [mss 1460,nop,nop,sackOK,nop,wscale 8,mptcp capable[bad opt]>
IP 192.0.2.1.46505 > 192.168.175.218.8080: Flags [.], ack 1, win 257, options [mptcp capable {0x837fb64bfcf2b75d,0x837fb64bfcf2b75d}], length 0
IP 192.168.175.218.8080 > 192.0.2.1.46505: Flags [F.], seq 1, ack 1, win 256, options [mptcp dss ack 10248370067666493757], length 0
IP 192.0.2.1.46505 > 192.168.175.218.8080: Flags [R.], seq 1, ack 1, win 257, length 0```

**Comment by dcaratti** [comment]
it looks like the problem is here, and also in the original packetdrill-mptcp project:

https://github.com/dcaratti/packetdrill/blob/784b72242af23f6250ea6f8824bd2acc6c59c3aa/gtests/net/packetdrill/mptcp.c#L472

the length of ``MP_CAPABLE`` option in outbound SYN+ACK should  be tested against ```TCPOLEN_MP_CAPABLE``` (20 octets), not ```TCPOLEN_MP_CAPABLE_SYN``` (12  octets).  @matttbe, is this correct?

**Comment by dcaratti** [comment]
> the length of `MP_CAPABLE` option in outbound SYN+ACK should be tested against `TCPOLEN_MP_CAPABLE` (20 octets), not `TCPOLEN_MP_CAPABLE_SYN` (12 octets). @matttbe, is this correct?

... it's not. mptcp-net-next wrongly echoes the client's key in SYN/ACK, and tcpdump [refuses](https://github.com/the-tcpdump-group/tcpdump/blob/master/print-mptcp.c#L181) to dissect v0 options where the SYN is set and option length is different than 12. Fixing mptcp-net-next to emit SYN+ACK packets having mp_capable options with a single key (the client one, according to [RFC6824](https://tools.ietf.org/html/rfc6824#section-3.1)) proved to fix both issues.

**Comment by matttbe** [comment]
@dcaratti it seems that when you edit a `@<someone>`, the new user is not notified :-)

Thank you for finding the bug and the fix :-)

**Comment by dcaratti** [comment]
fixed on Linux with https://patchwork.ozlabs.org/patch/1204700/
